server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venturenix_ol?useSSL=false
    username: oscarlo
    password: oscarVenturenixLab2023.
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      # hbm2ddl:
      #   import_files: /resources/data.sql
    hibernate:
      ddl-auto: update

# spring:
#   datasource:
#     url: jdbc:mysql://projectol-database.ctcmiocmq3o5.ap-southeast-1.rds.amazonaws.com:3306/venturenix_ol?useSSL=false&serverTimezone=UTC
#     username: projectOLadmin
#     password: projectOL
#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#         ddl-auto: update # Automatically update the database schema
#     open-in-view: false # Disable the open-in-view feature to improve performance

# App Properties
bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000
